apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: worker-cluster
spec:
  clusterNetwork:
    # pods:
    #   cidrBlocks:
    #   - 10.240.0.0/16
    services:
      cidrBlocks:
      - 10.0.0.0/16
    serviceDomain: cluster.local  
  controlPlaneRef:
    apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureManagedControlPlane
    name: worker-cluster
  infrastructureRef:
    apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureManagedCluster
    name: worker-cluster
---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedControlPlane
metadata:
  name: worker-cluster
spec:
  defaultPoolRef:
    name: wcagentpool0
  location: eastus
  resourceGroupName: capirg
  nodeResourceGroupName: capi-nodepool-rg
  sshPublicKey: ""
  subscriptionID: 0fe1cc35-0cfa-4152-97d7-5dfb45a8d4ba
  version: v1.19.6
  # networkPolicy: azure # or calico
  networkPlugin: kubenet # azure or kubenet
---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedCluster
metadata:
  name: worker-cluster
---
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: wcagentpool0
spec:
  clusterName: worker-cluster
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: worker-cluster
      infrastructureRef:
        apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AzureManagedMachinePool
        name: wcagentpool0
      version: v1.19.6
---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedMachinePool
metadata:
  name: wcagentpool0
spec:
  osDiskSizeGB: 512
  sku: Standard_D8s_v3