apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: south-aks-helm-release
  namespace: capi-worker-clusters
spec:
  chart:
    spec:
      chart: ./capi/mngmt/aks-cluster-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m
  values:
    name: south-aks
    clusterResourceGroup: south-aks-rg
    controlAgentPoolName: clsopool
    workerAgentPoolName: wrsopool

