apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: west-aws-helm-release
  namespace: capi-worker-clusters
spec:
  chart:
    spec:
      chart: ./capi/charts/aws/eks-cluster-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m
  values:
    name: west-voyager
    location: us-west-2    
    k8sVersion: v1.21.2
    workerAgentPoolNodes: 1
    workerAgentPoolNodeSize: t2.medium
