apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: east-test-helm-release
  namespace: capi-worker-clusters
spec:
  chart:
    spec:
      chart: ./capi/charts/azure/aks-cluster-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m
  values:
    name: east-test
    clusterResourceGroup: east-test-rg
    controlAgentPoolName: cletpool
    workerAgentPoolName: wretpool
    virtualNetwork:
      name: veast-test-vnet


