apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: east-voyager-helm-release
  namespace: capi-worker-clusters
spec:
  chart:
    spec:
      chart: ./capi/charts/azure/aks-cluster-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 10m
  values:
    name: east-voyager
    clusterResourceGroup: voyager-rg
    controlAgentPoolName: clevpool
    workerAgentPoolName: wrevpool
    virtualNetwork:
      name: voyager-vnet


