  
name: PR

on:
  pull_request:
    branches: [main]

jobs:
  code_quality_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'woke'
        uses: get-woke/woke-action@v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true
          # See https://github.com/marketplace/actions/get-all-changed-files for more options
          # woke-args: ${{ steps.files.outputs.added_modified }}
      # - uses: TrueBrain/actions-flake8@master
      #   name: Linting
      #   if: "true"
      #   with:
      #     path: ./src    
      # - uses: hadolint/hadolint-action@v1.5.0
      #   name: Docker Linting
      #   with:
      #     dockerfile: ./src/Dockerfile
      # - name: MD Linting
      #   uses: actionshub/markdownlint@main     